version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      - TZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 3306:3306
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
